# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_local_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='local',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
