# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20180423_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
