# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_auto_20180423_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ('name',)},
        ),
    ]
