# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_local'),
        ('local', '0008_local_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='product',
        ),
        migrations.AddField(
            model_name='local',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
