# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_auto_20180423_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
