# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local', '0010_auto_20180424_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='local',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='local', to=settings.AUTH_USER_MODEL),
        ),
    ]
