# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0011_auto_20180427_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='local_Local', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='local',
            name='product',
            field=models.ManyToManyField(related_name='local_Local', to='product.Product'),
        ),
    ]
