# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
