# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
        ('product', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local'),
        ),
    ]
