# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='local',
        ),
    ]
