# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_local'),
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
