# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
        ('mall', '0002_mall_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='product',
        ),
        migrations.AddField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local'),
        ),
    ]
