# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20180423_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mall',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Local'),
        ),
    ]
