# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20180423_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Local'),
        ),
    ]
