# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20180423_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mall',
            options={},
        ),
        migrations.RemoveField(
            model_name='mall',
            name='local',
        ),
    ]
