# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_local_product'),
        ('mall', '0008_auto_20180423_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='local',
        ),
        migrations.AddField(
            model_name='mall',
            name='local',
            field=models.ManyToManyField(to='local.Local'),
        ),
    ]
