# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0010_auto_20180424_1822'),
        ('mall', '0009_auto_20180423_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='local',
        ),
        migrations.AddField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='local.Local'),
            preserve_default=False,
        ),
    ]
