# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0010_auto_20180424_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='highlighted',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='mall',
            name='owner',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='mall', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='mall_Mall', to='local.Local'),
        ),
    ]
