# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_auto_20180427_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_Mall', to='local.Local'),
        ),
    ]
